name: Docker Build Release

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: pre-step
        shell: bash
        run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
      - name: Publish release to dockerhub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: linagora/twake-workplace-user-manager
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          context: .
          buildoptions: "-t linagora/twake-workplace-user-manager -f Dockerfile"
          tags: "${{ steps.pre-step.outputs.release-version }}"
